# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-22 07:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Name')),
                ('app', models.CharField(max_length=50, unique=True, verbose_name='App')),
                ('model', models.CharField(max_length=50, unique=True, verbose_name='Model')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('createtime', models.DateTimeField(auto_now_add=True, verbose_name='Create time')),
                ('updatetime', models.DateTimeField(auto_now=True, verbose_name='Update time')),
            ],
        ),
        migrations.CreateModel(
            name='PermissionList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='App Name')),
                ('createtime', models.DateTimeField(auto_now_add=True, verbose_name='Create time')),
                ('updatetime', models.DateTimeField(auto_now=True, verbose_name='Update time')),
                ('permissions', models.ManyToManyField(to='permission.Permission')),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('createtime', models.DateTimeField(auto_now_add=True, verbose_name='Create time')),
                ('updatetime', models.DateTimeField(auto_now=True, verbose_name='Update time')),
            ],
        ),
        migrations.CreateModel(
            name='RoleMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createtime', models.DateTimeField(auto_now_add=True, verbose_name='Create time')),
                ('updatetime', models.DateTimeField(auto_now=True, verbose_name='Update time')),
                ('member', models.ManyToManyField(to='permission.Permission')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='permission.Role')),
            ],
        ),
        migrations.CreateModel(
            name='RolePermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createtime', models.DateTimeField(auto_now_add=True, verbose_name='Create time')),
                ('updatetime', models.DateTimeField(auto_now=True, verbose_name='Update time')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='permission.Role')),
                ('permission', models.ManyToManyField(to='permission.Permission')),
            ],
        ),
    ]
