# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-16 14:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django_hstore.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('createtime', models.DateTimeField(auto_now_add=True, verbose_name=b'Create time')),
                ('updatetime', models.DateTimeField(auto_now=True, verbose_name=b'Update time')),
            ],
        ),
        migrations.CreateModel(
            name='Characteristic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('schema', django_hstore.fields.DictionaryField()),
                ('createtime', models.DateTimeField(auto_now_add=True, verbose_name=b'Create time')),
                ('updatetime', models.DateTimeField(auto_now=True, verbose_name=b'Update time')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eq_characteristics', to='cmdb.Category')),
            ],
        ),
        migrations.CreateModel(
            name='CharacteristicValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=100)),
                ('createtime', models.DateTimeField(auto_now_add=True, verbose_name=b'Create time')),
                ('updatetime', models.DateTimeField(auto_now=True, verbose_name=b'Update time')),
                ('characteristic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eq_key_values', to='cmdb.Characteristic')),
            ],
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('createtime', models.DateTimeField(auto_now_add=True, verbose_name=b'Create time')),
                ('updatetime', models.DateTimeField(auto_now=True, verbose_name=b'Update time')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cg_equip_list', to='cmdb.Category')),
            ],
        ),
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(max_length=50, unique=True)),
                ('ip', models.GenericIPAddressField()),
                ('other_ip', models.CharField(blank=True, max_length=100, null=True)),
                ('asset_no', models.CharField(blank=True, max_length=50, null=True)),
                ('asset_type', models.CharField(blank=True, choices=[(b'1', b'\xe7\x89\xa9\xe7\x90\x86\xe6\x9c\xba'), (b'2', b'\xe8\x99\x9a\xe6\x8b\x9f\xe6\x9c\xba'), (b'3', b'\xe5\xae\xb9\xe5\x99\xa8'), (b'4', b'\xe7\xbd\x91\xe7\xbb\x9c\xe8\xae\xbe\xe5\xa4\x87'), (b'5', b'\xe5\x85\xb6\xe4\xbb\x96')], max_length=30, null=True)),
                ('status', models.CharField(blank=True, choices=[(b'1', b'\xe4\xbd\xbf\xe7\x94\xa8\xe4\xb8\xad'), (b'2', b'\xe6\x9c\xaa\xe4\xbd\xbf\xe7\x94\xa8'), (b'3', b'\xe6\x95\x85\xe9\x9a\x9c'), (b'4', b'\xe5\x85\xb6\xe5\xae\x83')], max_length=30, null=True)),
                ('os', models.CharField(blank=True, max_length=100, null=True)),
                ('vendor', models.CharField(blank=True, max_length=50, null=True)),
                ('cpu_model', models.CharField(blank=True, max_length=100, null=True)),
                ('cpu_num', models.CharField(blank=True, max_length=100, null=True)),
                ('memory', models.CharField(blank=True, max_length=30, null=True)),
                ('disk', models.CharField(blank=True, max_length=255, null=True)),
                ('sn', models.CharField(blank=True, max_length=60)),
                ('position', models.CharField(blank=True, max_length=100, null=True)),
                ('memo', models.TextField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='HostGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('desc', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Idc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, null=True)),
                ('address', models.CharField(blank=True, max_length=100, null=True)),
                ('tel', models.CharField(blank=True, max_length=30, null=True)),
                ('contact', models.CharField(blank=True, max_length=30, null=True)),
                ('phone', models.CharField(blank=True, max_length=30, null=True)),
                ('cabinet', models.CharField(blank=True, max_length=30, null=True)),
                ('ip_range', models.CharField(blank=True, max_length=30, null=True)),
                ('bandwidth', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'verbose_name': 'idc',
                'verbose_name_plural': 'idc',
            },
        ),
        migrations.CreateModel(
            name='InterFace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('vendor', models.CharField(max_length=30, null=True)),
                ('bandwidth', models.CharField(max_length=30, null=True)),
                ('tel', models.CharField(max_length=30, null=True)),
                ('contact', models.CharField(max_length=30, null=True)),
                ('startdate', models.DateField()),
                ('enddate', models.DateField()),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='IpSource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('net', models.CharField(max_length=30)),
                ('subnet', models.CharField(max_length=30, null=True)),
                ('describe', models.CharField(max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30, null=True)),
                ('password', models.CharField(max_length=30, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='host',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cmdb.HostGroup'),
        ),
        migrations.AddField(
            model_name='host',
            name='idc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cmdb.Idc'),
        ),
        migrations.AddField(
            model_name='characteristicvalue',
            name='equipment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eq_characteristic_values', to='cmdb.Equipment'),
        ),
    ]
