# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-17 04:45
from __future__ import unicode_literals

from django.db import migrations, models
import django_hstore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True, verbose_name=b'Description'),
        ),
        migrations.AddField(
            model_name='characteristic',
            name='description',
            field=models.TextField(blank=True, verbose_name=b'Description'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='description',
            field=models.TextField(blank=True, verbose_name=b'Description'),
        ),
        migrations.AlterField(
            model_name='characteristic',
            name='schema',
            field=django_hstore.fields.DictionaryField(editable=False, null=True),
        ),
    ]
