# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-31 05:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0002_auto_20171217_0445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='name',
            field=models.CharField(max_length=100, verbose_name=b'Name'),
        ),
    ]
