# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-01 12:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0003_auto_20171231_0521'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='createtimes',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name=b'Create time'),
            preserve_default=False,
        ),
    ]
