# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-01 13:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0004_category_createtimes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='createtimes',
        ),
    ]
